
var psuedo_db = [
	"Hello world!",
	"That quick brown fox was jumping all around",
	"The quick brown fox was jumping all around",
	"The quick brown fox jumps over lazydawgs",
	"The quick brown fox jumps over a lazy dog",
	"Sphinx of black quartz, judge my vow.",
	"The previous pigeon tempers the crystal answer.",
	"Over the definite minimalist overlaps this grateful drama.",
	"A shortened analogue baffles the percentage on top of the acoustic client.",
	"An abbreviated analog confuses the rate on top of the acoustic customer.",
	"Will the client deduce the modern paint?",
	"An egg attacks!",
	"Does the outstanding immortal reach past the absolute?",
	"Our still-competitor lands the aircraft next to his opening taste.",
	"A sushi-centric motif, but with so many pairs of chopsticks, and only one piece of sushi",
	"What is this trying to say? There are ways of thinking that don't exist yet",
	"What is this trying to say? There are ways of thinking that haven't been invented",
	"What is this trying to say? There are ways of thinking that haven't been discovered",
	"What is this trying to say? There are ways of thinking that haven't been thought of",
	"What is this trying to say? There are ways of thinking that haven't been thought of yet",
	"What are you trying to say?",
	"Who are *you*?",
	"This isn't trying to solve a problem.",
	"I want to explore.",
	"I implore you to explore the text galore",
	"where there's text, there's always more",
	"there's always more, there's always more",
	"there's always more... there's always more...",
	"The medium is the message.",
	"The Medium is the Message",
	"The Medium is the Massage",
	"The Medium is the Mess Age",
	"The Medium is the Mass Age",
	"Diverge at every letter",
	"Diverge at every word and any letter",
	"Diverge at any word or letter",
	"alphabeta-magneta",
	"alphabetic-magnetic",
	"alphabetically magnetic",
	"start from nothing",
	"start from nothing, end up with something",
	"start from nothing, end up somewhere you didn't expect",
	"start from something, end up somewhere you didn't expect",
	"Textploration incarnate.",
	"A new medium of text.",
	"A new medium for text.",
	"A medium for massaging text.",
	"A new medium for textploration.",
	"It's a bit of a surprise to see you again for the first time.",
	"Once upon a time,",
	"Once upon a time, there was a",
	"Once upon a time, there was a time that wasn't once; it was twice and it was thrice, all because of a device.",
	"Once upon a time, there was a time that wasn't once; it was twice and it was thrice, all because of this device. It was",
	"The utter minimalism of a centered blinking cursor is appealing.",
	"while the world was not perfect, we could and would make it better.",
	"i can work with that.",
	"QWERTYUIOPASDFGHJKLZXCVBNM 1234567890 `~-_=+[{]}\\|;:'\",<.>/?",
	"qwertopia",
	"ABCDEFGHIJKLMNOPQRSTUVWXYZ",
	"asdlkjlakjdflskjdf",
	"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec fringilla sed arcu id consequat. Nulla nec urna sed lectus semper cursus. Nunc quis rhoncus elit, sed tincidunt odio. Sed ornare fringilla sem, non fringilla nibh sagittis eget. Integer commodo nulla elit, in efficitur augue venenatis eget. Proin id metus vel neque convallis sagittis eget eu turpis. Nulla lacinia nec sem et posuere. Aliquam ex magna, lacinia sed erat a, accumsan ullamcorper nunc. Integer non est sodales, mollis lorem egestas, molestie mauris. Fusce pharetra leo sit amet urna porttitor, at eleifend tortor maximus.",
	"]0301/134429.526:ERROR:exception_handler_server.cc(524)] ConnectNamedPipe: The pipe is being closed. (0xE8)"
];

function DatabaseProvider(){
	
}

DatabaseProvider.prototype.query = function(){
	return psuedo_db;
};

export default DatabaseProvider;
